### ISSUE TITLE
int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by andreykryazhev** [andymccurdy/redis-py#1438]
**Version**: redis==2.10.3

**Platform**: Python 2.7.13

**Description**:

Hi, I have the strange error (which reported via Sentry) on remote machine which I cannot reproduce locally. The traceback is:

```
TypeError: int() argument must be a string or a number, not 'NoneType'
  File "v2/core/rq/base.py", line 523, in check_horses
    event.delete()
  File "v2/core/rq/redis.py", line 346, in delete
    self._connection.delete(self._key)
  File "redis/client.py", line 824, in delete
    return self.execute_command('DEL', *names)
  File "redis/client.py", line 565, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "redis/client.py", line 579, in parse_response
    return self.response_callbacks[command_name](response, **options)  # Sentry shows that response is None here
```

The error happens pretty seldom: ~10 times per day and sometimes I see same traceback but cause is slightly different: 

```
TypeError: int() argument must be a string or a number, not 'list'
  <...>
  File "redis/client.py", line 579, in parse_response
    return self.response_callbacks[command_name](response, **options)
```

Can somebody help why **None** or **list** can be returned for DEL command?

**Comment by andymccurdy** [comment]
What version of Redis server are you using on the remote machine? You're also running a very old version of redis-py. Can you tried upgrading to a more recent version?

**Comment by andreykryazhev** [comment]
Redis-server version is **5.0.6**
At this time we cannot update to newer version (but is a plan to future).

**Comment by andymccurdy** [comment]
This sounds like a race condition to me as DEL should never be returning null or list responses. It might be due to a bug in the lib (that has likely been fixed in more recent versions) or a misuse of the library.

Are you in the threaded or forked environment?

**Comment by andreykryazhev** [comment]
Yes, many number of processes actively communicate with Redis. I also though that sometimes instead of result for DEL I got result for some other command, but still do not understand how this possible.

**Comment by andymccurdy** [comment]
redis-py uses a connection pool to share connections between threads. It's likely that there's a bug in the version of redis-py that you're using related to thread handling. As I said above, many (hopefully all!) of these bugs have been fixed in newer versions.

**Comment by andreykryazhev** [comment]
Understood, thank you.

**Comment by andymccurdy** [comment]
Closing this for now. If you upgrade and still have issues, please feel free to reopen.
