### ISSUE TITLE
redis-py client side hang; is there a stale or timeout re-connect paramter?

### ISSUE THREAD

**Issue by c0b** [andymccurdy/redis-py#722]
can reproduce this from a simple python shell, make a redis connection and let it idle for some time (some hours or I don't know what's the actual server side timeout), try a get all keys call, or any other call, it takes 930 seconds to return, or 15 minutes, this is a simple test server only have a few small keys, and get all keys by normal is just 0.003 second, so I suppose it's the idling has caused either side closed the connection, but why can't the client side detect it earlier, raise an exception, or do something earlier? I tried normal connection or ConnectionPool doesn't help;

``` python
In [18]: r = redis.Redis(connection_pool=redis.ConnectionPool(host='redis-server-...', port=6379, db='0'))

## idle for some hours

In [37]: start = datetime.now(); print r.keys(); end = datetime.now(); print "{:.3f} seconds".format((end - start).total_seconds())
# printed keys...
930.306 seconds
```

I'm reading the document https://pypi.python.org/pypi/redis don't see an stale option or client side timeout option?

https://github.com/andymccurdy/redis-py/issues?q=hang I have searched this there are many hang problems, however I am not seeing a duplicate

**Comment by andymccurdy** [comment]
You can use the `socket_timeout=num_seconds` option when creating a client instance to control how long to wait for a response before raising a TimeoutError.

Most of these types of issues are related to network issues. Routers or other appliances often shutdown idle TCP streams. You can also try using the `socket_keepalive=True` option to turn on standard TCP keepalive.

**Comment by c0b** [comment]
then what's the logic after 15 minutes it returned? is 930 seconds the default timeout?

**Comment by andymccurdy** [comment]
By default the client will wait indefinitely for a response, never raising an error.

Are the client and server running on the same machine? If not, it sounds like you have some kind of network issue.

**Comment by c0b** [comment]
not on the same machine but in the same datacenter network,

does redis-py client has some logging level can I turn on for debugging logs? I want to understand why after 930 seconds it must be re-connecting?

or would you suggest change server side config to give a timeout in this case? from http://redis.io/topics/clients#client-timeouts it seems server side doesn't set timeout by default

**Comment by c0b** [comment]
I confirmed it's not the `keys` call, even a `ping` call can take 15 minutes to return, after idling for hours; in normal it's just 3 ms

```python
In [54]: start = datetime.now(); print r.ping(); end = datetime.now(); print "{:.3f} seconds".format((end - start).total_seconds())
True
0.003 seconds
```

**Comment by c0b** [comment]
can I suggest for the pooling api to follow the peewee style to support a `max_connections` and `stale_timeout` parameter? I use peewee to connect mysql server as well that has a server side timeout, with peewee I can use a connection pool with stale_timeout set to slightly less than server side timeout, then it works perfect

http://docs.peewee-orm.com/en/latest/peewee/playhouse.html?highlight=stale#pool-apis

**Comment by andymccurdy** [comment]
There is not any debug logging in place currently. I'd like to understand why things magically work again after ~900 seconds as well. That's never come up before.

**Comment by c0b** [comment]
then if you know more ways to debug this problem? what is it doing during that 930 seconds hanging? here I can reproduce it's always 930. seconds;

from `netstat -antp` I can figured out all connection to redis-server's 6379 port is this python shell, `lsof` shows it has made 3 established tcp connections to redis server, `strace` showing it's waiting input on `fd:7`

```console
python2.7 31357 john    5u  IPv4 3353759       0t0     TCP 10.0.50.227:54716->10.5.8.30:6379 (ESTABLISHED)
python2.7 31357 john    6u  IPv4 3622332       0t0     TCP 10.0.50.227:35542->10.5.8.30:6379 (ESTABLISHED)
python2.7 31357 john    7u  IPv4 3664212       0t0     TCP 10.0.50.227:37282->10.5.8.30:6379 (ESTABLISHED)

$ strace -p 31357
strace: Process 31357 attached
recvfrom(7, 
```

**Comment by andymccurdy** [comment]
Looks like the client is blocking on a `socket.recv()` call.

You could prove this is a network issue by installing a redis-server on the same machine as the client with the same configuration and dataset. Point the client at the local instance. My guess is you won't be able to reproduce the same timeouts. Assuming you don't see any blocking, then it's something on your network that's messing with the TCP connection.

Also, as you mentioned above, configuring the server to timeout idle connections is worth trying. You shouldn't need to change anything on the client side. An idle client connection should automatically reconnect when the next command is executed.

**Comment by c0b** [comment]
right; that's easy to prove if I run a python shell on the redis-server and the same code never timeout or hang for 15 minutes, but I need to understand this network situation, I did ss to show TCP internal information and tcpdump listening on port 6379:

```console
$ ss -n4ti -o state established '( dport == 6379 )'
State      Recv-Q Send-Q                         Local Address:Port                                        Peer Address:Port              
ESTAB      0      14                               10.0.50.227:38620                                          10.5.8.30:6379                
timer:(on,42sec,13)
         ts sack cubic wscale:7,7 rto:120000 backoff:13 rtt:2.34/0.62 ato:40 mss:1448 cwnd:1 ssthresh:7 send 5.0Mbps lastsnd:77239 lastrcv:2
863224 lastack:2863224 pacing_rate 99.0Mbps unacked:1 retrans:1/14 lost:1 rcv_space:29200

## while strace is still running in background:
sendto(7, "*1\r\n$4\r\nPING\r\n", 14, 0, NULL, 0) = 14
recvfrom(7, "+PONG\r\n", 65536, 0, NULL, NULL) = 7        <= hanging here for 15 minutes to get data

## tcpdump -i eth0 -vvXX tcp port 6379

    10.0.50.227.38620 > 10.5.8.30.6379: Flags [P.], cksum 0x4f3a (incorrect -> 0x49ea), seq 28:42, ack 15, win 229, options [nop,nop,TS val 1665157632 ecr 137547475], length 14
        0x0000:  6487 8810 1090 b8ae ed78 cd34 0800 4500  d........x.4..E.
        0x0010:  0042 d90f 4000 4006 12a1 0a00 32e3 0a05  .B..@.@.....2...
        0x0020:  081e 96dc 18eb 5487 171f 7372 b597 8018  ......T...sr....
        0x0030:  00e5 4f3a 0000 0101 080a 6340 4a00 0832  ..O:......c@J..2
        0x0040:  ced3 2a31 0d0a 2434 0d0a 5049 4e47 0d0a  ..*1..$4..PING..


## Syn pack started a new TCP connection, with a new sport 38740 => redis-server:6379
02:07:01.639262 b8:ae:ed:78:cd:34 > 64:87:88:10:10:90, ethertype IPv4 (0x0800), length 74: (tos 0x0, ttl 64, id 55272, offset 0, flags [DF], proto TCP (6), length 60)
    10.0.50.227.38740 > 10.5.8.30.6379: Flags [S], cksum 0x4f34 (incorrect -> 0x8fc0), seq 3417765868, win 29200, options [mss 1460,sackOK,T
S val 1665277956 ecr 0,nop,wscale 7], length 0
        0x0000:  6487 8810 1090 b8ae ed78 cd34 0800 4500  d........x.4..E.
        0x0010:  003c d7e8 4000 4006 13ce 0a00 32e3 0a05  .<..@.@.....2...
        0x0020:  081e 9754 18eb cbb6 f7ec 0000 0000 a002  ...T............
        0x0030:  7210 4f34 0000 0204 05b4 0402 080a 6342  r.O4..........cB
        0x0040:  2004 0000 0000 0103 0307                 ..........


# sysctl -a |grep tcp_retries
net.ipv4.tcp_retries1 = 3
net.ipv4.tcp_retries2 = 15

```

from tcpdump's output it seems triggered Linux TCP Stack retransmitting, it retries and retries at interval 200ms, 200ms, 400ms, 800ms, 1600ms, and doubling timeout interval till 2min, and retries totally for 18 retries; got the results `200 + 200 + 400 + 800 + 1600 + 3200 + 6400 + 12800 + 25600 + 51200 + 102400 + 120000 * 6 ~= 930 seconds`; then it gave up and make a new TCP connection to server port 6379;

**Comment by tjsail33** [comment]
Is it possible to have redis-py detect when the connections go stale and reconnect? We are seeing this issue across many servers as well.

**Comment by andymccurdy** [comment]
@tjsail33 If you set a `socket_timeout`, redis-py will break the connection and retry the command if it waits long enough.

**Comment by natedub** [comment]
@tjsail33 an imperfect solution is to extend the `ConnectionPool.get_connection` method and throw away connections that have been in existence for too long. To do this, you just call `conn.disconnect()` before returning it — it will reconnect on first use. Works for us.

SQLAlchemy uses this same technique for mysql connections (called `pool_recycle`) which throw "connection reset by peer" errors if they're idle for too long.

**Comment by adam-benayoun** [comment]
@c0b What did you end up doing? Any solution to this?

**Comment by c0b** [comment]
:wow: what a surprise I got ping'ed one year later; one year is a pretty long time in the Internet industry that almost equals to forever; and this one remains open in the whole past year without any other one's comments, so I assume not many ones care about (or not many users of this library); let me just close it; what happened in our project is switched to others, no redis at all.

**Comment by adam-benayoun** [comment]
c0b, I am trying to use socket_timeout, did you try that? Did it fail? It's hard for me to reproduce this, so maybe you can save me some time :) thanks!

**Comment by andymccurdy** [comment]
I was never able to reproduce this behavior. I'd be happy to merge a fix or even make one myself if I could repro it.

**Comment by c0b** [comment]
sorry, too late; no longer in the original team and no longer have access.

**Comment by fuyb** [comment]
Hi.
Can I use the **socket_connect_timeout**=num_seconds option?
Sorry, my English is bad.
Thanks.

**Comment by samfrances** [comment]
I have found this problem surfacing after about a week on AWS. Definitely still an issue.

**Comment by reywood** [comment]
Experiencing this issue with celery running on EC2 instances using AWS's Elasticache (redis) for the celery backend. When trying to set a value to redis, it occasionally hangs for almost exactly 15 minutes and then it succeeds. Setting `socket_timeout` does mitigate the issue a bit, but waiting for the timeout does still slow things down. Just thought others might like to know that using `socket_timeout` did work, in my case at least.

**Comment by Morriaty-The-Murderer** [comment]
Hi  we have met this error too, and the hang duration is exactly 15min28sec273milli

**Comment by int3rlop3r** [comment]
We also have encountered the same issue. Finding it hard to reproduce.

```
$ strace -p 59978
strace: Process 59978 attached
recvfrom(16
```

**Comment by Ondrysak** [comment]
probably encountering the same issue, anybody found a hotfix? setting keepalive and timeout doesnt seem to help.

using gevent.timeout in our case so it gets killed 

```
File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 1697, in zadd
    return self.execute_command('ZADD', name, *pieces)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 624, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 390, in read_response
    bufflen = recv_into(self._sock, self._buffer)
  File "/usr/local/lib/python3.6/site-packages/redis/_compat.py", line 82, in recv_into
    return sock.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 385, in recv_into
    self._wait(self._read_event)
  File "/usr/local/lib/python3.6/site-packages/gevent/_socket3.py", line 157, in _wait
    self.hub.wait(watcher)
  File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 651, in wait
    result = waiter.get()
  File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 899, in get
    return self.hub.switch()
  File "/usr/local/lib/python3.6/site-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.timeout.Timeout: 180 seconds

```

**Comment by cgthayer** [comment]
fwiw, ran into this issue for deployments on kubernetes in GKE / GCP (Google Cloud Platform, Kubernetes Engine) and setting socket_keepalive=True didn't help, although adding socket_timeout=300 did.

```
self.redis = StrictRedis.from_url(self.url, socket_keepalive=True, socket_timeout=300)
```

**Comment by whusnoopy** [comment]
> same issue，930 second hang， redis client 2.10.5 version

I will hang on redis client 2.10.6, but everything goes will with 3.2.1, you can try a new version to check the issue is fixed or not

**Comment by willseeyou** [comment]
same issue, 930 seconds hang, redis client 3.2.1 version

**Comment by andymccurdy** [comment]
For those still experiencing this issue I would encourage you to upgrade to the latest 3.3.x and enable health checks with `health_check_interval=N` where `N` is the number of seconds a connection can be idle before a health check is initiated.

This can be combined with `socket_timeout` to help ensure lively connections.

**Comment by ss75710541** [comment]
I had the same problem, but I hung for 72 minutes

The key code is as follows

```
pool = redis.ConnectionPool(host=REDIS_HOST, port=REDIS_PORT, password=REDIS_PASSWORD, db=REDIB_DB,
                            health_check_interval=10, socket_connect_timeout=32, socket_keepalive=True)
r = redis.Redis(connection_pool=pool)

    logging.info("get queue")
    try:
        queue = r.brpop(DYNAMIC_QUEUE_NAME, 30)
    except Exception as e:
        logging.error("Unexpected error: %s" %e.args)
        logging.exception(e)
        return ("", None)
```

strace 

```
strace -p 26440
strace: Process 26440 attached
recv(3,
```

**Comment by ss75710541** [comment]
There is no problem with the redis I set up on the Intranet, but the redis of aliyun can be accessed through the external network

**Comment by andymccurdy** [comment]
If you're using blocking commands like `BRPOP` I'd suggest setting `socket_connect=N` and specifying `N - 5` as the timeout to `BRPOP`. Then run the `BRPOP` in a loop like this:

```python

pool = redis.ConnectionPool(..., socket_timeout=30)
r = redis.Redis(connection_pool=pool)

while True:
    try:
        queue = r.brpop('my-key', 25)
    except redis.TimeoutError:
        queue = None
    if queue is None:
        continue
    # do something with the queue value
```

This will make sure that the `BRPOP` doesn't block forever.

**Comment by MisLink** [comment]
I inherited `ConnectionPool` class to drop "old" connections directly:
```python
class ConnectionPool(redis.ConnectionPool):
    def reset(self):
        super().reset()
        self._connection_created_time = weakref.WeakKeyDictionary()

    def get_connection(self, command_name, *keys, **options):
        "Get a connection from the pool"
        self._checkpid()
        try:
            connection = self._available_connections.pop()
            if time.time() - self._connection_created_time[connection] > 1800:
                connection.disconnect()
                raise IndexError
        except IndexError:
            connection = self.make_connection()
		...

    def make_connection(self):
        connection = super().make_connection()
        self._connection_created_time[connection] = time.time()
        return connection
```
It's not a good strategy, but I think this kind of config to recycle connections is necessary 😀

BTW, If my understanding is correct, setting `socket_timeout` still hang client, just not 15mins, but `socket_timeout` secs.

**Comment by ss75710541** [comment]
@andymccurdy 

I'm still 2:35 hang，2:50 I restart the program and it works

I have a strange question. Every day is 2:35 and 14:35 hang

code
```
pool = redis.ConnectionPool(host=REDIS_HOST, port=REDIS_PORT, password=REDIS_PASSWORD, db=REDIB_DB,
                            health_check_interval=10, socket_connect=30, socket_keepalive=True)
r = redis.Redis(connection_pool=pool)

while(True):
    logging.info("get queue")
    try:
        queue = r.brpop(DYNAMIC_QUEUE_NAME, 25)
    except redis.TimeoutError:
        queue = None
        return ("", None)

    if queue == None :
        logging.info("%s no record." %DYNAMIC_QUEUE_NAME)
        return ("", None)
    logging.info(queue)
```

log

```
2020-01-19 02:34:44,319 [INFO] get queue
2020-01-19 02:35:09,381 [INFO] rmq::queue::[dynamicVideoQueue]::ready no record.
2020-01-19 02:35:09,381 [INFO] sleep 10
2020-01-19 02:35:19,394 [INFO] get queue
2020-01-19 02:50:16,393 [INFO] get queue
2020-01-19 02:50:41,624 [INFO] rmq::queue::[dynamicVideoQueue]::ready no record.
2020-01-19 02:50:41,624 [INFO] sleep 10
```

**Comment by andymccurdy** [comment]
@ss75710541 The argument is `socket_timeout`, not `socket_connect`.

**Comment by ss75710541** [comment]
@andymccurdy  Ok, thanks. I'll try again

**Comment by Andrew-Chen-Wang** [comment]
@andymccurdy Redis 3.2 has TCP keep alive option with timeout 300 seconds as default for dead peers. I've not been able to re-produce the problem here, but the issue does somewhat worry me (that's how I originally encountered this GitHub issue). Link to the TCP keep alive option: https://redis.io/topics/clients (at the bottom). Does that resolve this issue or is TCP keepalive's 300 seconds the same as `socket_timeout=300`?

And just to double check, if the connection goes dead, then re-accessing a variable of type `redis.Redis` should re-open a connection, right? Thanks!

**Comment by andymccurdy** [comment]
@ss75710541 `socket_timeout` applies to all blocking socket operations. `socket_connect_timeout` applies only to blocking during the initial TCP handshake.

**Comment by andymccurdy** [comment]
@Andrew-Chen-Wang TCP Keep Alive is separate from `socket_timeout`.

TCP Keep Alive is a technique where both sides of a TCP connection will send random data back and forth so that network devices between the two sides see regular activity. redis-py supports this if you enable the `socket_keepalive` (boolean) and `socket_keepalive_options` (platform dependent) values.

`socket_timeout` instructs the client side of the connection to only block up to `socket_timeout` seconds on any blocking socket operation.

If a connection goes dead, the connection pool should detect that the next time a connection is retrieved from the pool. You can use the `health_check_interval` option to make sure the connection is tested at least every `health_chech_interval` seconds. If you experience a lot of random disconnects in your environment this option can greatly help alleviate that.

**Comment by esseti** [comment]
Is anyone experiencing this problem just when behind a proxy? I've noticed that i've timeouts only if i pass via a HA proxy. If connecting directly to redis there are no random timeouts.
can it be that py - HA has a way to check stale connections, and drops that. while ha-redis has another way, and it may be that there's no talking between the parts on resetting connections? (it's strange anyway)

**Comment by andymccurdy** [comment]
@esseti HAProxy has a number of configuration options to control timing out of idle connections. See the "timeout" section in the HAProxy docs starting here: https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-timeout%20check

**Comment by mschfh** [comment]
from looking at the code, setting a `health_check_interval` triggers `PING` commands, which would also be affected by the connection timeout?
https://github.com/redis/redis-py/blob/bea72995fd39b01e2f0a1682b16b6c7690933f36/redis/connection.py#L755-L759


(I ran into this while researching a CLUSTER FAILOVER related issue, )
